### ISSUE TITLE
Specifying the #[link] to ntdll on each symbol individually results in spam to the linker

### ISSUE THREAD

**Issue by retep998** [MSxDOS/ntapi#2]
[This is a bug in Rust](https://github.com/rust-lang/rust/issues/38460), but I'm opening an issue here regardless.

![screenshot of linker command line which is ntdll.lib repeated a million times](https://user-images.githubusercontent.com/666308/83129660-22af7f80-a0ab-11ea-9236-8df8921161b5.png)

**Comment by MSxDOS** [comment]
https://github.com/rust-lang/rust/pull/84794
