### ISSUE TITLE
Replace winapi with windows-sys?

### ISSUE THREAD

**Issue by Jake-Shadle** [MSxDOS/ntapi#9]
I was updating `mio` to use `windows-sys` instead of `winapi` as `windows-sys` covers most of Windows API surface and most importantly is maintained and updated frequently as opposed to `winapi`, but this crate still provides types and functions not available in the `windows-sys` crate which is to be expected, however since it relies on `winapi` internally we'll be pulling in 2 versions of windows bindings, and in some cases need to transmute between the "same" type, so just wanted to open this issue to begin a discussion about whether this is something that would be acceptable to this project.

**Comment by ghost** [comment]
I agree on this one, winapi can already be seen as deprecated, since there is the official windows crate.

https://github.com/microsoft/windows-rs
https://crates.io/crates/windows-sys

**Comment by Skgland** [comment]
Why was this closed as completed?

**Comment by Jake-Shadle** [comment]
I was pruning issues I'd opened that hadn't gotten any response or that I don't care about any longer.

**Comment by Skgland** [comment]
Wouldn't closing as not planned be more appropriate then? (Maybe with a small comment)

<img width="480" height="242" alt="Image" src="https://github.com/user-attachments/assets/2dc86b58-3c7c-441f-9709-8082ca7d7a5e" />

Would a PR doing the change still be appreciated?

**Comment by Jake-Shadle** [comment]
It's not my repo, #17 already exists.

**Comment by Skgland** [comment]
> It's not my repo

Ah, I overlooked that. A bit unfortunate that issue authors can't choose a different close reason.

> #17 already exists.

Yeah, I saw that that PR exists, but it has merge conflicts and hasn't been updated in three years.

**Comment by Skgland** [comment]
> but it has merge conflicts and hasn't been updated in three years.

Ah, I don't think the PR actually has blocking merge conflicts, GitHub UI is just contradicting itself.

Can it be cleanly merged or are there conflicts that __*must*__ be resolved!?

<img width="410" height="72" alt="Image" src="https://github.com/user-attachments/assets/8012bc86-f83e-4e89-a97e-37aff0811a17" />
